---
# tasks file for common

- name: install ca package
  yum: name=ca-certificates state=present

- name: install internal CA certificate
  copy:
    src: "{{ item }}"
    dest: /etc/pki/ca-trust/source/anchors
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - ca/*
  notify:
    - update trusted ca

- name: configure internal repository
  template: src=internal.repo dest=/etc/yum.repos.d/internal.repo
