---
# tasks file for kibana

- name: install kibana repo
  copy:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0644

- name: install kibana
  yum: name=kibana state=present update_cache=yes

- name: install kibana configuration file
  template:
    src: kibana.yml.j2
    dest: /opt/kibana/config/kibana.yml
  notify: restart kibana

- name: start kibana
  service: name=kibana state=started
